"""Adding db schema

Revision ID: 0824b1fe13f7
Revises: 
Create Date: 2023-08-23 13:16:31.631330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0824b1fe13f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('privileges_is_available', sa.Boolean(), nullable=True),
    sa.Column('max_players_in_shelter', sa.Integer(), nullable=True),
    sa.Column('chat_name', sa.String(), nullable=True),
    sa.Column('start_message_id', sa.String(), nullable=True),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.Column('disaster', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('time_spent', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('build_reason', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('room_1', sa.String(), nullable=True),
    sa.Column('room_2', sa.String(), nullable=True),
    sa.Column('room_3', sa.String(), nullable=True),
    sa.Column('available_resource_1', sa.String(), nullable=True),
    sa.Column('available_resource_2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_settings_id'), 'games', ['settings_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.Column('diamonds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_settings_id'), 'users', ['settings_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('msg_id', sa.String(), nullable=True),
    sa.Column('person_msg_id', sa.String(), nullable=True),
    sa.Column('card_msg_id', sa.String(), nullable=True),
    sa.Column('voices_to_kick', sa.Integer(), nullable=True),
    sa.Column('is_dead', sa.Boolean(), nullable=True),
    sa.Column('is_need_to_be_in_rekick_vote', sa.Boolean(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('is_job_open', sa.Boolean(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('is_sex_open', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_age_open', sa.Boolean(), nullable=True),
    sa.Column('hobby', sa.String(), nullable=True),
    sa.Column('is_hobby_open', sa.Boolean(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('is_personality_open', sa.Boolean(), nullable=True),
    sa.Column('fear', sa.String(), nullable=True),
    sa.Column('is_fear_open', sa.Boolean(), nullable=True),
    sa.Column('luggage', sa.String(), nullable=True),
    sa.Column('is_luggage_open', sa.Boolean(), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('is_health_open', sa.Boolean(), nullable=True),
    sa.Column('add_inf', sa.String(), nullable=True),
    sa.Column('is_add_inf_open', sa.Boolean(), nullable=True),
    sa.Column('knowledge', sa.String(), nullable=True),
    sa.Column('is_knowledge_open', sa.Boolean(), nullable=True),
    sa.Column('card_1', sa.String(), nullable=True),
    sa.Column('is_card_1_open', sa.Boolean(), nullable=True),
    sa.Column('card_2', sa.String(), nullable=True),
    sa.Column('is_card_2_open', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_settings_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_settings_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('settings')
    # ### end Alembic commands ###
