"""add chat table

Revision ID: 11cb7aaee76e
Revises: 7b031a13ff0e
Create Date: 2023-09-03 20:56:39.838726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cb7aaee76e'
down_revision = '7b031a13ff0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
