"""add add_skip_button_in_kick_vote in setting table; add final_vote_msg_id and likes in game table

Revision ID: 20b6211f9b66
Revises: 611d9a77edba
Create Date: 2023-09-01 21:54:53.940053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b6211f9b66'
down_revision = '611d9a77edba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('final_vote_msg_id', sa.String(), nullable=True))
    op.add_column('games', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('add_skip_button_in_kick_vote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'add_skip_button_in_kick_vote')
    op.drop_column('games', 'likes')
    op.drop_column('games', 'final_vote_msg_id')
    # ### end Alembic commands ###
