"""04 09 23

Revision ID: 28d9d06a9d13
Revises: 43c9a2d634b3
Create Date: 2023-09-04 23:24:18.959288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d9d06a9d13'
down_revision = '43c9a2d634b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
