"""add host_user_id in game table

Revision ID: 43a3c38fe83d
Revises: 4aed3b188da6
Create Date: 2023-09-01 13:03:52.390687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a3c38fe83d'
down_revision = '4aed3b188da6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('host_user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_games_settings_id', table_name='games')
    op.create_index(op.f('ix_games_host_user_id'), 'games', ['host_user_id'], unique=False)
    op.drop_constraint('games_settings_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'settings', ['host_user_id'], ['id'])
    op.drop_column('games', 'settings_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('settings_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_settings_id_fkey', 'games', 'settings', ['settings_id'], ['id'])
    op.drop_index(op.f('ix_games_host_user_id'), table_name='games')
    op.create_index('ix_games_settings_id', 'games', ['settings_id'], unique=False)
    op.drop_column('games', 'host_user_id')
    # ### end Alembic commands ###
