"""04 09 23

Revision ID: 43c9a2d634b3
Revises: 5db753077d0c
Create Date: 2023-09-04 22:32:05.764701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c9a2d634b3'
down_revision = '5db753077d0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('voices_to_skip', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('add_skip_btn_in_vote', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('silence_for_kicked', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('silence_for_unplayed', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('silence_during_voice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'silence_during_voice')
    op.drop_column('settings', 'silence_for_unplayed')
    op.drop_column('settings', 'silence_for_kicked')
    op.drop_column('settings', 'add_skip_btn_in_vote')
    op.drop_column('games', 'voices_to_skip')
    # ### end Alembic commands ###
