"""add host_user_id in game table hotfix

Revision ID: 45d56e92d7f5
Revises: 43a3c38fe83d
Create Date: 2023-09-01 13:05:00.114998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d56e92d7f5'
down_revision = '43a3c38fe83d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_host_user_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['host_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_host_user_id_fkey', 'games', 'settings', ['host_user_id'], ['id'])
    # ### end Alembic commands ###
