"""change setting table

Revision ID: 4aed3b188da6
Revises: b390ef4bbf86
Create Date: 2023-09-01 12:45:20.897159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aed3b188da6'
down_revision = 'b390ef4bbf86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'current_players_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('current_players_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
