"""add chats table

Revision ID: 4cda01405134
Revises: 20b6211f9b66
Create Date: 2023-09-03 20:00:11.303683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cda01405134'
down_revision = '20b6211f9b66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(), nullable=True),
    sa.Column('chat_telegram_id', sa.String(), nullable=True),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_settings_id'), 'chats', ['settings_id'], unique=False)
    op.drop_index('ix_users_settings_id', table_name='users')
    op.drop_constraint('users_settings_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'settings_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_settings_id_fkey', 'users', 'settings', ['settings_id'], ['id'])
    op.create_index('ix_users_settings_id', 'users', ['settings_id'], unique=False)
    op.drop_index(op.f('ix_chats_settings_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
