"""add is_like_btn_pressed in player table

Revision ID: 5db753077d0c
Revises: 6c94ad45232c
Create Date: 2023-09-04 13:15:28.460014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db753077d0c'
down_revision = '6c94ad45232c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_like_btn_pressed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_like_btn_pressed')
    # ### end Alembic commands ###
