"""add is_open_param in players table

Revision ID: 611d9a77edba
Revises: cba9b2cdb9cd
Create Date: 2023-09-01 20:38:10.967150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611d9a77edba'
down_revision = 'cba9b2cdb9cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_open_param', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_open_param')
    # ### end Alembic commands ###
