"""add dislikes in game table

Revision ID: 6c94ad45232c
Revises: ddb42bb01a04
Create Date: 2023-09-04 13:12:25.820869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c94ad45232c'
down_revision = 'ddb42bb01a04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'dislikes')
    # ### end Alembic commands ###
