"""delete host_id in game table

Revision ID: 7b031a13ff0e
Revises: 4cda01405134
Create Date: 2023-09-03 20:04:09.411834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b031a13ff0e'
down_revision = '4cda01405134'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_host_id', table_name='games')
    op.drop_constraint('games_host_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'host_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('games_host_id_fkey', 'games', 'users', ['host_id'], ['id'])
    op.create_index('ix_games_host_id', 'games', ['host_id'], unique=False)
    # ### end Alembic commands ###
