"""hotfix table settings

Revision ID: 7b446e357638
Revises: 11cb7aaee76e
Create Date: 2023-09-03 20:57:54.739486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b446e357638'
down_revision = '11cb7aaee76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
