"""Adding exchange_add to settings

Revision ID: 7d9a9c0c01c1
Revises: 0824b1fe13f7
Create Date: 2023-08-24 19:37:56.568286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9a9c0c01c1'
down_revision = '0824b1fe13f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('exchange_add', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'exchange_add')
    # ### end Alembic commands ###
