"""host_user_id -> host_id

Revision ID: ae95698bd28e
Revises: 45d56e92d7f5
Create Date: 2023-09-01 13:39:24.816896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae95698bd28e'
down_revision = '45d56e92d7f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('host_id', sa.Integer(), nullable=True))
    op.drop_index('ix_games_host_user_id', table_name='games')
    op.create_index(op.f('ix_games_host_id'), 'games', ['host_id'], unique=False)
    op.drop_constraint('games_host_user_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['host_id'], ['id'])
    op.drop_column('games', 'host_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('host_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_host_user_id_fkey', 'games', 'users', ['host_user_id'], ['id'])
    op.drop_index(op.f('ix_games_host_id'), table_name='games')
    op.create_index('ix_games_host_user_id', 'games', ['host_user_id'], unique=False)
    op.drop_column('games', 'host_id')
    # ### end Alembic commands ###
