"""adding money to User table

Revision ID: b390ef4bbf86
Revises: b8246b7d0561
Create Date: 2023-08-28 20:35:45.528524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b390ef4bbf86'
down_revision = 'b8246b7d0561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'money')
    # ### end Alembic commands ###
