"""move setting params from table game to table setting

Revision ID: b8246b7d0561
Revises: 7d9a9c0c01c1
Create Date: 2023-08-28 18:09:24.565736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8246b7d0561'
down_revision = '7d9a9c0c01c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('current_players_count', sa.Integer(), nullable=True))
    op.drop_column('games', 'privileges_is_available')
    op.drop_column('games', 'max_players')
    op.drop_column('games', 'max_players_in_shelter')
    op.add_column('settings', sa.Column('max_players_in_shelter', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('privileges_is_available', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('max_players', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'max_players')
    op.drop_column('settings', 'privileges_is_available')
    op.drop_column('settings', 'max_players_in_shelter')
    op.add_column('games', sa.Column('max_players_in_shelter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('max_players', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('privileges_is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('games', 'current_players_count')
    # ### end Alembic commands ###
