"""add is_dead to game players

Revision ID: cba9b2cdb9cd
Revises: e68625e72f04
Create Date: 2023-09-01 19:58:20.367466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba9b2cdb9cd'
down_revision = 'e68625e72f04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_vote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_vote')
    # ### end Alembic commands ###
