"""add premium to chat table

Revision ID: ddb42bb01a04
Revises: 7b446e357638
Create Date: 2023-09-03 21:10:33.692644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb42bb01a04'
down_revision = '7b446e357638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'premium')
    # ### end Alembic commands ###
