"""add invite_link to game table

Revision ID: e68625e72f04
Revises: fb32f50ef888
Create Date: 2023-09-01 14:52:36.659489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68625e72f04'
down_revision = 'fb32f50ef888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('invite_link_to_chat', sa.String(), nullable=True))
    op.drop_column('games', 'redirection_to_private_btn_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('redirection_to_private_btn_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'invite_link_to_chat')
    # ### end Alembic commands ###
