"""add redirection_to_private_btn_id to game table

Revision ID: fb32f50ef888
Revises: ae95698bd28e
Create Date: 2023-09-01 14:35:39.340699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb32f50ef888'
down_revision = 'ae95698bd28e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('redirection_to_private_btn_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'redirection_to_private_btn_id')
    # ### end Alembic commands ###
